### PR TITLE
Show recommended solution for resolved assignments

### PR DESCRIPTION
**Pull request by martinzugnoni**
"Show recommended solution" button will only show up for assignments that were already resolved by the student and that contains a defined solution in the database.

solution

### CODE REVIEW

**Comment by tychovk** [comment]
Hi Martin, is there any way to just have a button for it? Or would we have to submit everything all over again in the assignments we have already finished successfully. I just want to see optimal "pythonic" solutions for simple cases. Learn it right from the get-go.

**Comment by santiagobasulto** [comment]
+1

**Comment by santiagobasulto** [comment]
@tychovk, there's a button showing the proposed solution. But you will only see it after you've solved the given assignment. Am I right  @martinzugnoni ?

**Comment by martinzugnoni** [comment]
Right, and also only for assignments that have a defined solution in our database. (most of them have though)

**Comment by tychovk** [comment]
I've solved pretty much all of them, checked all of them and I can't find the button!

**Comment by santiagobasulto** [comment]
@tychovk I don't think it's deployed yet :)

**Comment by martinzugnoni** [comment]
I've just deployed the code. It's working now.

**Comment by tychovk** [comment]
Okay, that wasn't clear to me :-), I can see some now, about 5 of them. Hopefully more will come before we get to the end of the course! 

Good job implementing it!

**Comment by martinzugnoni** [comment]
;-)

**Comment by tychovk** [comment]
Please let us know when the buttons are actually operational! :-)

**Comment by martinzugnoni** [comment]
It is operational now. I've just tried it and works fine. Remember, you must first resolve the assignment to see the button, and the assignment must have an available solution to display. :)

**Comment by tychovk** [comment]
Hi Martin, I can see the button just fine, but clicking it does nothing... I can click show test cases, back to lecture, submit.. but nothing pops up with show recommendation. I've had them resolved since Sat/Sunday I think...

(https://sis.rmotr.com/assignments/12?next=/courses/lectures/23 trying it here).

**Comment by martinzugnoni** [comment]
Try this one for example: https://sis.rmotr.com/assignments/13?next=/courses/lectures/23

As there's been some JS changes, make sure to hard refresh the page so cached JS code is updated.

**Comment by tychovk** [comment]
Perfect. Hard refresh did it! Thanks for guiding me through it ;-)

**Comment by martinzugnoni** [comment]
Welcome ;-)

**Pull request merged**
